name: CI

on:
  push:
    paths:
      - 'ProductCatalog/**'
      - '.github/workflows/main.yaml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Dependencies
        run: go mod download

      - name: Build
        run: go build -o catalog_api_server ./cmd/catalog_api_server

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Dependencies
        run: go mod download

      - name: Linter
        run: go vet ./...

      - name: Tests
        run: go test -v ./...

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Pull Docker image
        run: docker pull madfisher/catalog-api:latest

      - name: Run Docker container
        run: docker run -d -p 8080:8080 madfisher/catalog-api:latest

