name: CI

on:
  push:
    paths:
      - 'catalog_api/**'
      - '.github/workflows/main.yaml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Dependencies
        working-directory: ./catalog_api
        run: go mod download

      - name: Linter
        working-directory: ./catalog_api
        run: go vet ./...

      - name: Tests
        working-directory: ./catalog_api
        run: go test -v ./...

