name: CI

on:
  push:
    paths:
      - 'ProductCatalog/**'
      - '.github/workflows/main.yaml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Dependencies
        working-directory: ./ProductCatalog
        run: go mod download

      - name: Linter
        working-directory: ./ProductCatalog/catalog_api
        run: go vet ./...

      - name: Tests
        working-directory: ./ProductCatalog/catalog_api
        run: go test -v ./...

      - name: Build
        working-directory: ./ProductCatalog/catalog_api
        run: go build -o catalog_api_server ./cmd/catalog_api_server

      - name: Run Migrations
        working-directory: ./ProductCatalog/scripts/database
        run: go run migrate.go

#      - name: Deploy
#        run: |


      - name: Notify Success
        if: always()
        uses: rtCamp/action-slack-notify@v2
        with:
          status: success
          text: "CI успешно завершен"
